[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
custom_test_frameworks = true
panic-abort-tests = true
[build]
target = "custom_target.json"


[target.'cfg(test)']
runner = "bootimage runner"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"


